config/routes.rb
FmlApp::Application.routes.draw do
  root :to => 'messages#index'

  get "static_pages/home"

  get "static_pages/help"

  match "messages/delete/:id" => "messages#destroy", :as => "delete", :via => "post"

  resources :messages do
    resources :replies
  end

end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :answer, :challenge_question, :content, :score, :title
  has_many :replies, :dependent => :destroy

  validates :title, :content, :challenge_question, :answer,  :presence => true
  validates :title, :length => {:maximum => 200}

end

app/models/reply.rb
class Reply < ActiveRecord::Base
  attr_accessible :content, :message_id
  belongs_to :message
  validates :content, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
    @messages = @messages.sort{|y, x|(x.id) <=> (y.id)}

    respond_to do |format|
      format.html # index_bk.html.erb
      format.json { render json: @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @message = Message.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/new
  # GET /messages/new.json
  def new
    @message = Message.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(params[:message])
    @message.score = 0
    @message.content = @message.content + " FML!"


    respond_to do |format|
      if @message.save
        format.html { redirect_to messages_url, notice: 'Message was successfully created.' }
        format.json { render json: @message, status: :created, location: @message }
      else
        format.html { render action: "new" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /messages/1
  # PUT /messages/1.json
  def update
    @message = Message.find(params[:id])

    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message = Message.find(params[:id])
    respond_to do |format|
      if params[:attempt].eql?(@message.answer)
        @message.destroy
        @messages = Message.all
        format.html { redirect_to messages_url, notice: 'Message was successfully deleted.' }
      else
        format.html { redirect_to @message, notice: 'your answer is wrong, unable to delete the post' }
      end
    end
  end

  def reply
    @message = Message.find(params[:id])
    @reply = @message.replies.create(:content => params[:content], :message_id => params[:id])
    respond_to do |format|
      if @reply.save
        @messages = Message.all
        format.html { redirect_to messages_url, notice: 'successfully replied.' }
      else
        format.html { redirect_to @message, notice: 'unable to reply' }
      end
    end
  end

  def get_count
    Message.count
  end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  def index
    @message = Message.find(params[:message_id])
   # @replies = @message.replies

    respond_to do |format|
      format.html # index_bk.html.erb
    end

  end

  def create
    @message = Message.find(params[:message_id])
    @reply = @message.replies.create(:content => params[:attempt], :message_id => @message.id)
    respond_to do |format|
      if @reply.save
        @messages = Message.all
        format.html { redirect_to messages_url, notice: 'successfully replied.' }
      else
        format.html { redirect_to message_replies_url(@message), notice: 'unable to reply' }
      end
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<header class="header">
  <div class="link">
            <li><%= link_to "Help", help_page %></li>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fuck My Life: seeing how others sucks in life!</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :a_challenge_question_used_to_delete_post %><br />
    <%= f.text_field :challenge_question %>
  </div>
  <div class="field">
    <%= f.label :answer %><br />
    <%= f.text_field :answer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<%= javascript_include_tag "main" %>
<%= javascript_include_tag :defaults %>
<h1 xmlns="http://www.w3.org/1999/html">Welcome to FML</h1>
<div id="post">
  <%= link_to 'Post A New FML Message', new_message_path %>
</div>

<div id="container">
  <p id="notice"><%= notice %></p>
  <% @messages.each do |message| %>
    <div class="messageBox">
        <div class="titleBox">
          <%= message.title %>
        </div>
        <div class="content">
          <%= message.content %>
          <p class="createdAt">Created At: <%= message.created_at %></p>
          <p><%= link_to "delete", message %></p>
          <p><%= link_to "reply",  message_replies_url(message) %></p>
          </div>
            <% @replies = message.replies
               @replies = @replies.sort{|y, x|(x.id) <=> (y.id)}
            if @replies.length > 5
              @temp = Array.new(5);
              @temp[0] = @replies[0];
              @temp[1] = @replies[1];
              @temp[2] = @replies[2];
              @temp[3] = @replies[3];
              @temp[4] = @replies[4];
                @replies = @temp
            end
            %>
            <% if @replies.length == 0 %>
                <div class="replyList">
                There is no replies.<%= link_to "Reply Now",  message_replies_url(message) %>
            <% else %>
                <div class="replyList multiple">
            <% end %>
            <% @replies.each do |reply| %>
                <ul>
                    <li>
                        <%= reply.content %>
                    </li>
                </ul>
            <% end %>
            <% if message.replies.length > 5 %>
                <%= link_to "See more replies (" + (message.replies.length - 5).to_s + ")",  message_replies_url(message) %>
            <% end %>
          </div>
        </div>
  <% end %>
</div>

app/views/messages/new.html.erb
<h1 class="pageTitle">Post a new FML message</h1>
<%= form_for(@message) do |f| %>
    <% if @message.errors.any? %>
        <h2>Errors:</h2>
        <ul>
          <% @message.errors.full_messages.each do |m| %>
          <li>
            <%= m %>
          </li>
          <% end %>
        </ul>
        <% end %>
<div id="newMessageBox" class="messageBox">
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :a_challenge_question_used_to_delete_post %><br />
    <%= f.text_field :challenge_question %>
  </div>
  <div class="field">
    <%= f.label :answer %><br />
    <%= f.text_field :answer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <%= link_to 'Back', messages_path %>
</div>
<% end %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>
<div id="displayMessageBox" class="messageBox">
<p>
  <b>Title:</b>
  <%= @message.title %>
</p>

<p>
  <b>Content:</b>
  <%= @message.content %>
</p>

<p>
  <b>Challenge question:</b>
  <%= @message.challenge_question %>
</p>
<%= form_tag(delete_path, :params => params.merge(:answer => :attempt)) do %>
<div class="field">
  Answer:<br />
  <%= text_field_tag :attempt %>
</div>
<div class="submit">
    <%= submit_tag 'Delete' %>
</div>
<% end %>
</div>
<%= link_to 'Back', messages_path %>

app/views/replies/index.html.erb
<p id="notice" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html"><%= notice %></p>
<div id="displayMessageBox" class="messageBox">
  <p>
    <b>Title:</b>
    <%= @message.title %>
  </p>

  <p>
    <b>Content:</b>
    <%= @message.content %>
  </p>

  <p>
    <b>Score:</b>
    <%= @message.score %>
  </p>

  <%= form_tag(message_replies_url(@message), :content => :attempt) do %>
      <div class="field">
        Reply:<br />
        <%= text_field_tag :attempt %>
      </div>
      <div class="submit">
        <%= submit_tag 'Reply' %>
      </div>
  <% end %>
</div>
  <div class="messageBox">
    <% @message.replies.each do |reply| %>
        <ul>
          <li>
            <p></p><%= reply.content %></p>
            <p class="createdAt">Created At: <%= reply.created_at %></p>
            <hr>
          </li>
        </ul>
    <% end %>
  </div>
<%= link_to 'Back', messages_path %>

app/views/replies/new.html.erb
<h1>Replies#new</h1>
<p>Find me in app/views/replies/new.html.erb</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>
<div id="footer">
    <pre><%=  %></pre>
</div>"